export default{
    name:"comment",
    title:"Comment",
    type:"document",
    fields:[
        {
            name:"name",
            title:'Name',
            type:'string'
        },
        {
            name:"email",
            title:"Email",
            type:"string"
        },
        {
            name:"post",
            Title:"Post",
            type:'reference',
            to:[{type:'post'}]
        },
        {
            name:"approved",
            title:"Approved",
            type:'boolean'
        },
        {
            name:"comment",
            title:"Comment",
            type:"text"
        }
    ]
}